/* This file was generated by bfc-rs (https://github.com/ceilingfans/bfc-rs) */
#include <stdio.h>

int main()
{
    char arr[30000] = {0}; char* ptr = arr;
    while (*ptr)
    {
        *ptr = getchar();
        putchar(*ptr);
        while (*ptr)
        {
            putchar(*ptr);
        }
        *ptr = getchar();
        putchar(*ptr);
        putchar(*ptr);
        *ptr = getchar();
        *ptr = getchar();
        *ptr = getchar();
        *ptr += 1;
        *ptr = getchar();
        *ptr += -1;
        *ptr = getchar();
        *ptr = getchar();
        while (*ptr)
        {
        }
        putchar(*ptr);
        putchar(*ptr);
        putchar(*ptr);
        putchar(*ptr);
    }
    *ptr += 8;
    while (*ptr)
    {
        ptr += 1;
        *ptr += 4;
        while (*ptr)
        {
            ptr += 1;
            *ptr += 2;
            ptr += 1;
            *ptr += 3;
            ptr += 1;
            *ptr += 3;
            ptr += 1;
            *ptr += 1;
            ptr += -4;
            *ptr += -1;
        }
        ptr += 1;
        *ptr += 1;
        ptr += 1;
        *ptr += 1;
        ptr += 1;
        *ptr += -1;
        ptr += 2;
        *ptr += 1;
        while (*ptr)
        {
            ptr += -1;
        }
        ptr += -1;
        *ptr += -1;
    }
    ptr += 2;
    putchar(*ptr);
    ptr += 1;
    *ptr += -3;
    putchar(*ptr);
    *ptr += 7;
    putchar(*ptr);
    putchar(*ptr);
    *ptr += 3;
    putchar(*ptr);
    ptr += 2;
    putchar(*ptr);
    ptr += -1;
    *ptr += -1;
    putchar(*ptr);
    ptr += -1;
    putchar(*ptr);
    *ptr += 3;
    putchar(*ptr);
    *ptr += -6;
    putchar(*ptr);
    *ptr += -8;
    putchar(*ptr);
    ptr += 2;
    *ptr += 1;
    putchar(*ptr);
    ptr += 1;
    *ptr += 2;
    putchar(*ptr);
    return 0;
}
