
/* This file was generated by 'bfc-rs' (https://github.com/ceilingfans/bfc-rs) */
#include <stdio.h>

int main()
{
	char arr[30000] = {0}; char* ptr = arr;
	while (*ptr)
	{
		*ptr = getchar();
		putchar(*ptr);
		while (*ptr)
		{
			putchar(*ptr);
		}
		*ptr = getchar();
		putchar(*ptr);
		putchar(*ptr);
		*ptr = getchar();
		*ptr = getchar();
		*ptr = getchar();
		++*ptr;
		*ptr = getchar();
		--*ptr;
		*ptr = getchar();
		--ptr;
		++ptr;
		*ptr = getchar();
		while (*ptr)
		{
		}
		putchar(*ptr);
		putchar(*ptr);
		putchar(*ptr);
		putchar(*ptr);
	}
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	while (*ptr)
	{
		++ptr;
		++*ptr;
		++*ptr;
		++*ptr;
		++*ptr;
		while (*ptr)
		{
			++ptr;
			++*ptr;
			++*ptr;
			++ptr;
			++*ptr;
			++*ptr;
			++*ptr;
			++ptr;
			++*ptr;
			++*ptr;
			++*ptr;
			++ptr;
			++*ptr;
			--ptr;
			--ptr;
			--ptr;
			--ptr;
			--*ptr;
		}
		++ptr;
		++*ptr;
		++ptr;
		++*ptr;
		++ptr;
		--*ptr;
		++ptr;
		++ptr;
		++*ptr;
		while (*ptr)
		{
			--ptr;
		}
		--ptr;
		--*ptr;
	}
	++ptr;
	++ptr;
	putchar(*ptr);
	++ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	putchar(*ptr);
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	++*ptr;
	putchar(*ptr);
	putchar(*ptr);
	++*ptr;
	++*ptr;
	++*ptr;
	putchar(*ptr);
	++ptr;
	++ptr;
	putchar(*ptr);
	--ptr;
	--*ptr;
	putchar(*ptr);
	--ptr;
	putchar(*ptr);
	++*ptr;
	++*ptr;
	++*ptr;
	putchar(*ptr);
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	putchar(*ptr);
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	--*ptr;
	putchar(*ptr);
	++ptr;
	++ptr;
	++*ptr;
	putchar(*ptr);
	++ptr;
	++*ptr;
	++*ptr;
	putchar(*ptr);
	return 0;
}
